# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: "napkon-vaccination"
canonical: "https://www.napkon.de/fhir"
name: "NapkonVaccination"
title: "NAPKON Vaccination Module"
status: "active"
version: "1.0.0"
fhirVersion: "4.0.1"
copyrightYear: 2021+
releaseLabel: trial-use
publisher:
  name: "Charité - Universitätsmedizin Berlin"
  url: "https://www.netzwerk-universitaetsmedizin.de"
dependencies:
  de.medizininformatikinitiative.kerndatensatz.prozedur:
    uri: https://simplifier.net/guide/medizininformatikinitiative-modulprozeduren-implementationguide
    version: 2.0.0-alpha3
  de.medizininformatikinitiative.kerndatensatz.person:
    uri: https://simplifier.net/guide/medizininformatikinitiative-modulperson-implementationguide
    version: 2.0.0-alpha3
  de.medizininformatikinitiative.kerndatensatz.medikation:
    uri: https://simplifier.net/guide/medizininformatikinitiative-modulmedikation-implementationguide
    version: 1.0.10
  de.medizininformatikinitiative.kerndatensatz.diagnose:
    uri: https://simplifier.net/guide/medizininformatikinitiative-moduldiagnosen-implementationguide
    version: 2.0.0-alpha3
  de.medizininformatikinitiative.kerndatensatz.laborbefund:
    uri: https://simplifier.net/guide/laborbefundindermedizininformatik-initiative
    version: 1.0.6
  de.gecco:
    uri: https://simplifier.net/guide/germancoronaconsensusdataset-implementationguide
    version: 1.0.5
  de.medizininformatikinitiative.kerndatensatz.meta:
    uri: https://simplifier.net/guide/medizininformatikinitiative-implementationguide-manteldokument
    version: 1.0.3
  de.medizininformatikinitiative.kerndatensatz.fall:
    uri: https://simplifier.net/guide/medizininformatikinitiative-modulfall-implementationguide
    version: 1.0.1

pages:
  index.md:
    title: NAPKON Vaccination Module
  guidance.md:
  profiles.md:
  codesystems.md:
    title: Code Systems
  valuesets.md:
    title: Value Sets
  extensions.md:
  examples.md:
  downloads.xml:
  changelog.md:
    title: Change Log

menu:
  Home: index.html
  Guidance: guidance.html
  Profiles: profiles.html
  Code Systems: codesystems.html
  Value Sets: valuesets.html
  Examples: examples.html
  Downloads: downloads.html
  Change Log: changelog.html
